version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "SECRET_KEY=${DOCKER_COMPOSE_SECRET_KEY}"
      - "debug_status=True"
      - "email_password=${EMAIL_PASSWORD}"
      - "django_merchant_id=${DJANGO_COMPOSE_MERCHANT_ID}"
  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
