# Generated by Django 4.2.3 on 2024-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='add_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
