# Generated by Django 4.2.3 on 2024-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', 'very bad'), ('3', 'good'), ('2', 'bad'), ('5', 'excellent'), ('4', 'very good')]),
        ),
    ]
