# Generated by Django 4.2.3 on 2024-09-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='_(enter your comment)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, choices=[('4', 'very good'), ('1', 'very bad'), ('3', 'good'), ('2', 'bad'), ('5', 'excellent')], verbose_name='rate the product'),
        ),
    ]
