# Generated by Django 4.2.3 on 2024-10-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comment_body_alter_comment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='enter your comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, choices=[('3', 'good'), ('1', 'very bad'), ('4', 'very good'), ('5', 'excellent'), ('2', 'bad')], verbose_name='rate the product'),
        ),
    ]
