# Generated by Django 4.2.3 on 2024-10-04 18:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_comment_stars_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, choices=[('4', 'very good'), ('2', 'bad'), ('1', 'very bad'), ('3', 'good'), ('5', 'excellent')], verbose_name='rate the product'),
        ),
    ]
