# Generated by Django 4.2.3 on 2024-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_comment_body_alter_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='enter your comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, choices=[('3', 'good'), ('4', 'very good'), ('5', 'excellent'), ('2', 'bad'), ('1', 'very bad')], verbose_name='rate the product'),
        ),
    ]
