# Generated by Django 4.2.3 on 2024-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', 'very bad'), ('3', 'good'), ('2', 'bad'), ('5', 'excellent'), ('4', 'very good')], verbose_name='rate the product'),
        ),
    ]
